# Generated by Django 3.1.3 on 2020-11-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('price', models.BigIntegerField()),
                ('about', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seller', models.CharField(max_length=30)),
            ],
        ),
    ]
